language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - python setup.py install
  - pip install -r test_requirements.txt
# command to run tests
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
