sudo: false
language: python
python:
  - "2.7"
  - "3.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install -r test_requirements.txt
  - pip install six --upgrade --ignore-installed
# command to run tests
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
