language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install -r test_requirements.txt . --use-mirrors
# command to run tests
script:
  - coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
